version: '3'
name: lightfeatherio
services:
  frontend:
    build: ./client-app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./web-api
      dockerfile: WebServiceApp/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"